### PR TITLE
git: consider full refspec when determining seen refs

### LINKED ISSUE #4120: git lfs migrate import --everything doesn't migrate tags whose name matches that of a branch
**Describe the bug**
When migrating a repository to LFS, any tags that have the same name as a branch are not migrated. Presumably this is because somewhere inside LFS tags are referred to in am ambiguous way as `<name>` rather than `refs/tags/<name>`.

**To Reproduce**
```
git init .
git lfs install --local
echo "hello" > hello.txt
git add hello.txt
git commit -m "Add hello.txt"
git branch release_42
git tag release_42
git tag release_other
git lfs migrate import --everything --include="*.txt"
```

**Expected behavior**
Both branches (master and release_42) and both tags (release_42 and release_other) should all point to the same new, migrated commit.

**Observed behaviour**
The two branches and the release_other tag point to the same new, migrated commit. But the release_42 tag still points to the old, unmigrated commit.

**System environment**
Windows 10, Git Bash environment.

**Output of `git lfs env`**
```
git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
git version 2.26.2.windows.1

LocalWorkingDir=C:\Data\Code\repro
LocalGitDir=C:\Data\Code\repro\.git
LocalGitStorageDir=C:\Data\Code\repro\.git
LocalMediaDir=C:\Data\Code\repro\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Data\Code\repro\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Data\Code\repro\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

### PR DESCRIPTION
**Pull request by bk2204**
We avoid rewriting references that we've already seen, since in some cases we will need to order references to properly handle tags pointing to tags.  However, we use ref.Name for this, which is the short name, not the full refspec.  Consequently, if we've already seen a ref with the same short name (e.g., a branch when we're processing a tag), we end up skipping the second ref.

This is not what we want, so let's use the full refspec when populating the set of items we've already seen.

Fixes #4120
/cc @karlhendikse as reporter
/cc #3238, which may be fixed by this

### CODE REVIEW

File: git/githistory/rewriter.go [hunk 1]
```diff
@@ -554,6 +554,7 @@ func (r *Rewriter) refsToMigrate() ([]*git.Ref, error) {
 		}
 
 		local = append(local, ref)
+		fmt.Fprintf(os.Stderr, "dx: b: to migrate=%q\n", ref.Refspec())
```
Comment (chrisd8088) [inline git/githistory/rewriter.go:557]: Is this deliberate, or leftover from debugging, by any chance?

Comment (bk2204) [reply git/githistory/rewriter.go:557]: That is indeed debugging output.  I'll strip it out.
