### PR TITLE
commands: show real error while cleaning

### LINKED ISSUE #2060: fatal error: better error message desired when there's no space left
after initializing a repository in an existing project with 5+ GB of assets and issuing _git add ._
I've got this message:
```
Error cleaning asset.

Errors logged to /some/project/.git/lfs/objects/logs/20170320T192042.257426199.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs clean -- %f failed 2
error: external filter git-lfs clean -- %f failed
fatal: dir/1/some.mp3: clean filter 'lfs' failed
```

Turned out I was running out of space and freeing some 5+GB of additional space solved the puzzle.
Here git-lfs gave 2 useless suggestions: _git lfs log_ has nothing to shows and the log has 0 bytes. 

git-lfs/2.0.1 (GitHub; darwin amd64; go 1.8) / git-lfs/2.0.1 (GitHub; linux amd64; go 1.8)

### PR DESCRIPTION
**Pull request by technoweenie**
Adds a little more detail to the error message. Fixes #2060

### CODE REVIEW

File: commands/command_clean.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ func clean(to io.Writer, from io.Reader, fileName string) error {
 	}
 
 	if err != nil {
-		Panic(err, "Error cleaning asset.")
```
Comment (ttaylorr) [inline commands/command_clean.go]: I take it all back:

```
ExitWithError(errors.Wrap(err, "Error cleaning LFS object"))
```

since the stacktrace isn't helpful here.
