### PR TITLE
teach 'git lfs track' about CRLF

### LINKED ISSUE #1543: `git lfs track` uses LF on Windows
### Setup

```
git-lfs/1.4.1 (GitHub; windows amd64; go 1.7; git 2070e4c)
git version 2.9.2.windows.1 
Win 7 & Win 8.1
```
### Steps to reproduce

``` bash
$ git init .
$ touch test1
$ git add .
$ git commit -m "test1"
$ echo "large" > test2
$ git lfs track test2
$ git add .

warning: LF will be replaced by CRLF in .gitattributes.
The file will have its original line endings in your working directory.
```

I think `git lfs track` should use CRLF in the `.gitattributes` file on Windows to avoid this warning.

### PR DESCRIPTION
**Pull request by technoweenie**
This updates `git lfs track` to end lines written to in `.gitattributes` with a CRLF (`\r\n`) IF:

1. The file currently uses CRLF.
2. OR the `core.autocrlf` is `true` or `input`
3. OR it's running on windows.

Should fix #1543

### CODE REVIEW

File: test/test-track.sh [hunk 1]
```diff
@@ -99,16 +99,75 @@ begin_test "track without trailing linebreak"
...
-  fi
+  mkdir existing-crlf
+  cd existing-crlf
+  git init
+
+  git config core.autocrlf true
+  git lfs track "*.mov" "*.gif"
+  expected="*.mov filter=lfs diff=lfs merge=lfs -text^M$
+*.gif filter=lfs diff=lfs merge=lfs -text^M$"
+  [ "$expected" = "$(cat -e .gitattributes)" ]
```
Comment (technoweenie) [inline test/test-track.sh]: Whoop, shouldn't rely on the order of maps in go:

```
    + git lfs track '*.mov' '*.gif'
    + expected='*.mov filter=lfs diff=lfs merge=lfs -text^M$
    *.gif filter=lfs diff=lfs merge=lfs -text^M$'
    ++ cat -e .gitattributes
    + '[' '*.mov filter=lfs diff=lfs merge=lfs -text^M$
    *.gif filter=lfs diff=lfs merge=lfs -text^M$' = '*.gif filter=lfs diff=lfs merge=lfs -text^M$
    *.mov filter=lfs diff=lfs merge=lfs -text^M$' ']'
```
