### PR TITLE
commands: list explicitly excluded patterns separately

### LINKED ISSUE #2442: Tracked file patterns having `-filter=lfs` are not listed correclty
### Steps to reproduce
1. In the `.gitattributes` put the following lines:
```
*.zip filter=lfs diff=lfs merge=lfs -text
*.doc filter=lfs diff=lfs merge=lfs -text
```
2. In a subdirectory `core` put the following `.gitattributes`:
```
*.doc -filter=lfs diff=lfs merge=lfs -text
```
Note that the filter is prepended with "-" to NOT track `*.doc` files in this subdirectory.

3. Call `git lfs track` to list the patterns:
```
$ git lfs track
Listing tracked patterns
    core\*.doc (core\.gitattributes)
    *.zip (.gitattributes)
    *.doc (.gitattributes)
```
=> It is not visible that `core\*.doc` is NOT tracked

4. Add a `*.doc` file in the `core` subdirectory, comit and push to origin
=> The file is not tracked by LFS as desired

### Conclusion
When `.gitattributes` contains `-filter=lfs` the `-` seems not to be respected when listing tracked patterns. But for commiting and pushing the `-` is correctly interpreted.

### Environment
```
git-lfs/2.1.1 (GitHub; windows amd64; go 1.8.1; git 3314e287)
git version 2.13.2.windows.1
```

### PR DESCRIPTION
**Pull request by bk2204**
Currently, if a user has disabled Git LFS for a pattern in a .gitattributes file (such as in a subdirectory) by writing "-filter=lfs", we render the pattern as a tracked pattern in "git lfs track", even though those paths are not enabled for Git LFS.

Improve this situation by listing excluded patterns as well as tracked patterns.  Compute whether a pattern is excluded by looking for an attribute entry that starts with "-filter" and if so, list the entry as excluded.  Add tests for both the "-filter" and "-filter=lfs" situations.

Fix #2442.

### CODE REVIEW

File: git/attribs.go [hunk 1]
```diff
@@ -102,11 +105,14 @@ func attrPaths(path, workingDir string) []AttributePath {
 			continue
 		}
 
+		has_filter := strings.Contains(line, "filter=lfs")
```
Comment (ttaylorr) [inline git/attribs.go]: Nit: Go variables should be camel-cased.

Comment (bk2204) [reply git/attribs.go]: Ah, yes.  Will fix.

**Comment by bk2204** [comment]
I was slightly worried about the parsing issue as well, but rationalized it the way that you did in that this is a porcelain, not a plumbing command. I think a `--no-excluded` option would be a good middle ground, in that it provides people an escape route if they do want to continue to parse the output of `git lfs track`.

**Comment by bk2204** [comment]
Also, to respond to your suggestion about refactoring this, I think that is indeed a good idea, but I'd like to put that on the backlog for 2.7.0 instead of doing that here, and I'll open an issue to note that down.

**Comment by bk2204** [comment]
There's now a `--no-excluded` flag (and documentation) and I have stopped writing Rust-style variable names in Go.  I've also opened #3328 to document our planned refactor for 2.7.0.
