### PR TITLE
git-lfs: omit tags in ls-remote; optimize pre-push

### LINKED ISSUE #5848: Fetching all refs and tags on every push can be really slow for large repositories
**Describe the bug**
At the moment, doing a `git push` on a repository with `git lfs` enabled executes `git lfs pre-push`. One of the commands executed as a part of git pre-push seems to be — 

```
trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'ls-remote' '--heads' '--tags' '-q' 'origin'
```

In a very large repository, which has CI systems tagging releases every hour and a large number of refs, this currently takes ~10s to execute slowing down `git push` for everyone. 

**Expected behavior**
`--tags` are omitted or there is some sort of caching that avoids making a call to fetch all remotes on all pushes. Tags can be an ever-growing list and most git commands do not fetch tags by default (or it is possible to set fetching of tags off by default easily).

**Output of `git lfs env`**
```
git-lfs/3.5.1 (GitHub; darwin amd64; go 1.22.1)
git version 2.46.0

LocalReferenceDirs=
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneVerifyUnreachableAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/local/opt/git/libexec/git-core
GIT_TRACE2_PARENT_NAME=_run_dashed_
GIT_TRACE2_PARENT_SID=20240827T034806.415503Z-H0456b86c-P0000772d
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

### PR DESCRIPTION
**Pull request by pastelsky**
Fixes #5848.

Improves the performance of git lfs pre-push particularly for large repositories with numerous tags.

Previously, the pre-push hook would execute 'git ls-remote' with both --heads and --tags flags, which could be slow in repositories with many tags.

Tags can be omitted for pre-push however.

### CODE REVIEW

**Comment by chrisd8088** [comment]
Hey, thanks very much for the patch!  I'll take a look in the next few days, and consider whether we should add a test.

Our CI jobs are also not working 100% right now, so I won't kick off CI jobs for this PR yet, but I have some fixes in the pipeline and will get those up into a PR soon, so we can return our CI suite to full functionality.  Once that's done, we have a small queue of PRs like yours to merge.  So, stay tuned, and thanks very much for the contribution!

**Comment by pastelsky** [comment]
Thanks! My understanding was that this was just removing an unused flag from a code path, which is why I didn't add a test initially. What are the assertions we could add here in your opinion?

**Comment by chrisd8088** [comment]
> What are the assertions we could add here in your opinion?

Honestly, I haven't had time to even think about this yet -- it's entirely possible there's nothing we need to do.  I only meant to say that I try to always consider, for any PR, whether tests are something we can add or update.  It was just a generic comment.

Thanks for you patience, and once `$DAYJOB` is slightly less intensive, I should be able to get our CI stack working again.

**Comment by chrisd8088** [comment]
Just a quick update on the state of our CI suite: PR #5866 fixed the macOS jobs, PR #5868 should fix the Windows jobs, and PR #5872 will upgrade us to Go 1.23, which should fix the `Build with specific Go` jobs.  With any luck, we'll be back to 100% success after those are merged.

Thanks very much for your patience!

**Comment by pastelsky** [comment]
Thanks for the update, Chris.

Regards,
Shubham Kanodia

File: git/git.go [hunk 1]
```diff
@@ -1279,9 +1279,15 @@ func Fetch(remotes ...string) error {
...
-func RemoteRefs(remoteName string) ([]*Ref, error) {
+func RemoteRefs(remoteName string, ignoreTags bool) ([]*Ref, error) {
 	var ret []*Ref
-	cmd, err := gitNoLFS("ls-remote", "--heads", "--tags", "-q", remoteName)
+	args := []string{"ls-remote", "--heads", "-q"}
+	if !ignoreTags {
+		args = append(args, "--tags")
+	}
+	args = append(args, remoteName)
+
```
Comment (chrisd8088) [inline git/git.go:1289]: There's some extra trailing whitespace on this line which `go fmt` is detecting -- would you mind removing that?  That should allow our CI suite to pass.

File: lfs/gitscanner_remotes.go [hunk 2]
```diff
@@ -13,7 +13,7 @@ import (
 // remote, use a more explicit diff command.
 func calcSkippedRefs(remote string) []string {
 	cachedRemoteRefs, _ := git.CachedRemoteRefs(remote)
-	actualRemoteRefs, _ := git.RemoteRefs(remote)
+	actualRemoteRefs, _ := git.RemoteRefs(remote, true)
 
 	// The set of remote refs can be very large. Since CachedRemoteRefs only
 	// returns branches, filter the remote refs and convert them to a set for
```
Comment (chrisd8088) [inline lfs/gitscanner_remotes.go:19]: I notice that we can also simplify the following loop because we no longer need to filter for branch refs only.  I've written up that simplification and can push a commit to this branch, if you're willing to accept it.  Otherwise I'll put it into a separate branch in my fork, and you can take a look at it there.

**Review by chrisd8088 — COMMENTED** [review]
Thanks again for this PR!

I realized we could go a bit further with these changes, removing some unneeded logic and adding an error check, and that we should perhaps also expand our test suite of the `git lfs push` command slightly to cover the case where there is a tag ref on the Git remote.

I've written up three commits in my `ls-remote-skip-tags` [branch](https://github.com/chrisd8088/git-lfs/tree/ls-remote-skip-tags) and I'd like to push these into this PR's branch, if that's OK with you.

We'd then solicit a second review from another member of the core team, and that should be everything we need to get this merged!

Let me know if that's all acceptable.  I can also open a second PR, but I think it's easier to combine efforts here in this one, if possible.  If I don't hear back in a while, I may go ahead with my plan as I outlined it; I hope that's OK.

Thanks again for the contribution!

File: lfs/gitscanner_remotes.go (hunk 2 above)
Comment (pastelsky) [reply lfs/gitscanner_remotes.go:19]: Hey Chris, please feel free to add any commits to this.

**Comment by pastelsky** [comment]
@chrisd8088 You can add your commits to this, no issues.

**Comment by chrisd8088** [comment]
> You can add your commits to this, no issues — added you as a collaborator to my fork.

Thank you very much!  I've done so, and I'll solicit a review from another @git-lfs/core person (just so I'm not reviewing my own commits!), and we'll go from there.  Thanks again!

File: git/git.go [hunk 3]
```diff
@@ -1279,9 +1279,15 @@ func Fetch(remotes ...string) error {
 
 // RemoteRefs returns a list of branches & tags for a remote by actually
 // accessing the remote via git ls-remote.
-func RemoteRefs(remoteName string) ([]*Ref, error) {
+func RemoteRefs(remoteName string, ignoreTags bool) ([]*Ref, error) {
 	var ret []*Ref
-	cmd, err := gitNoLFS("ls-remote", "--heads", "--tags", "-q", remoteName)
+	args := []string{"ls-remote", "--heads", "-q"}
+	if !ignoreTags {
```
[the remark this answers is not in the document]
Comment (chrisd8088) [reply git/git.go]: Great suggestion, thank you!  I've adopted it and also took the opportunity to update the comments describing the function a bit too.
