### PR TITLE
Fix clash between progress meter and credential helper

### LINKED ISSUE #847: credential output hidden while transferring files
When Git LFS is uploading or downloading a batch of files, it shows some progress output. It hides any other output from the command, like `git-credentials` asking for your username and password. Here's what I see (scroll to the right to see the username prompt).

```
Git LFS: (1 of 4 files) 16.64 KB / 818.94 KB                                                                                                                                                                                                                                                                                                                               Username for 'https://github-cloud.s3.amazonaws.com':
Git LFS: (1 of 4 files) 101.27 KB / 818.94 KB
```

If you can't see the prompt, then git lfs appears to hang for no apparent reason. The only fix is to setup a credential cacher right now.

### PR DESCRIPTION
**Pull request by technoweenie**
This is an attempt to fix #847. It pauses the progress meter before making the batch api request, and then starts it when it passing the batch api response to the transfer adapters. This works because:

* `(progress.Meter) Start()`, `Finish()`, and `Pause()` internally use channels and `atomic/sync`. No need for that `sync.Once` in `tq.TransferQueue`.
* The `tq.TransferQueue` only transfers items from a single batch concurrently. The sequence (Batch API -> _n_ transfer adapter workers) runs sequentially, so that the next batch (if needed) can process the retries from the previous batch.

Unfortunately, there isn't really a way to test this, since it requires interactive input.  Here's an example of this PR working (with a tiny hack to change the batch size to 2):

```
$ git lfs fetch --all 2>&1
Scanning for all objects ever referenced...
✔ 9 objects found
Fetching objects...
Username for 'https://github.com': technoweenie
Password for 'https://technoweenie@github.com':
Git LFS: (0 of 9 files) 0 B / 1.03 MB                                                                                                                                                                                                        Username for 'https://github.com': technoweenie
Password for 'https://technoweenie@github.com':
Git LFS: (3 of 9 files) 356.27 KB / 1.03 MB                                                                                                                                                                                                  Username for 'https://github.com': technoweenie
Password for 'https://technoweenie@github.com':
Git LFS: (5 of 9 files) 886.59 KB / 1.03 MB                                                                                                                                                                                                  Username for 'https://github.com': technoweenie
Password for 'https://technoweenie@github.com':
Git LFS: (7 of 9 files) 948.33 KB / 1.03 MB                                                                                                                                                                                                  Username for 'https://github.com': technoweenie
Password for 'https://technoweenie@github.com':
Git LFS: (9 of 9 files) 1000.70 KB / 1.03 MB
```

Here's the same, without pausing:

```
$ git lfs fetch --all 2>&1
Scanning for all objects ever referenced...
✔ 9 objects found
Fetching objects...
Username for 'https://github.com': technoweenie
Password for 'https://technoweenie@github.com':
Git LFS: (1 of 9 files) 0 B / 1.03 MB                                                                                                                                                                                                        UGit LFS: (2 of 9 files) 0 B / 1.03 MB
```

### CODE REVIEW

File: progress/meter.go [hunk 1]
```diff
@@ -111,6 +111,12 @@ func (p *ProgressMeter) Start() {
 	}
 }
 
+func (p *ProgressMeter) Pause() {
+	if atomic.SwapInt32(&p.started, 0) == 1 {
```
Comment (ttaylorr) [inline progress/meter.go]: Nit: Using `atomic.CompareAndSwapInt32(&p.started, 1, 0)` accomplishes the same behavior.

File: tq/transfer_queue.go [hunk 2]
```diff
@@ -307,7 +307,7 @@ func (q *TransferQueue) enqueueAndCollectRetriesFor(batch batch) (batch, error)
 	}
 
 	q.useAdapter(bRes.TransferAdapterName)
-	q.startProgress.Do(q.meter.Start)
```
Comment (ttaylorr) [inline tq/transfer_queue.go]: Before we resume the progress meter, we have two opportunities to bail out early: on L302 and L306. I think both of those are fine, since we'd exit this function early, and the progress meter would get resumed the next time a new batch was enqueued. There'd be no issues with calling `Pause()` twice, since there's a `CompareAndSwap<T>` operation guarding the channel send into `p.finished`.

@technoweenie would you mind double checking my thinking on this?

File: progress/meter.go (hunk 1 above)
Comment (technoweenie) [inline progress/meter.go]: Ah good call. This was copy pasta from `Start()`, but I'll tweak both.

File: tq/transfer_queue.go (hunk 2 above)
Comment (technoweenie) [inline tq/transfer_queue.go]: Seems legit. I went ahead and added some tests in the `progress` package to assert that `Start()` and `Pause()` can be called multiple times.

**Comment by technoweenie** [comment]
Well, since I made `Start()` and `Pause()` safe for multiple calls, I went ahead and did the same for `Finish()`. Also, calling `Finish()` means that `Start()` and `Pause()` can never be called again.

**Comment by technoweenie** [comment]
Welp, those changes did not make things happier. I backed out of them in this PR.

**Comment by ttaylorr** [comment]
> Welp, those changes did not make things happier. I backed out of them in this PR.

👍
