### PR TITLE
Don't mark unlocked files that aren't lockable as read-only

### LINKED ISSUE #4169: Unlocking a file that is not `lockable` should not make the file read only
**Describe the bug**

If a file is locked (doesn't need to be tracked by LFS) and is not `lockable`, when unlocking the file it will be marked read only until the user manually corrects the permissions.

**To Reproduce**

```
# Setup a clean repo
mkdir lfs-repro
cd lfs-repro
git init
echo "# LFS test" > README.md
git add README.md
git commit -m "Init"

# Add a remote that supports LFS locking
git remote add origin https://github.com/jamesramsay/lfs-repro.git

# Lock and unlock
git lfs install
git lfs lock README.md
git lfs unlock README.md

# Observe read-only permissions
ls -la README.md
```

As far as I can tell, Git LFS never changes the permissions again, so they are stuck as read only until manually resolved.

**Expected behavior**

Since the file is not marked `lockable`, the file should not be set to read only when unlocked.

**System environment**

macOS 10.15.5

<details><summary>**Output of `git lfs env`**</summary>

```
git-lfs/2.11.0 (GitHub; darwin amd64; go 1.14.2)
git version 2.27.0

Endpoint=https://github.com/jamesramsay/lfs-repro.git/info/lfs (auth=none)
  SSH=git@github.com:jamesramsay/lfs-repro.git
LocalWorkingDir=/Users/jramsay/GitLab/temp/lfs-repro
LocalGitDir=/Users/jramsay/GitLab/temp/lfs-repro/.git
LocalGitStorageDir=/Users/jramsay/GitLab/temp/lfs-repro/.git
LocalMediaDir=/Users/jramsay/GitLab/temp/lfs-repro/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/jramsay/GitLab/temp/lfs-repro/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/jramsay/GitLab/temp/lfs-repro/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/local/Cellar/git/2.27.0/libexec/git-core
GIT_TRACE2_PARENT_NAME=_run_dashed_
GIT_TRACE2_PARENT_SID=20200625T025724.504881Z-H0bad8183-P00002d11
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

```

</details>

### PR DESCRIPTION
**Pull request by bk2204**
Whenever we use a file path filter and there are no included patterns, we default to assuming the files match.  For many cases, this is fine, but this is not useful for checking whether a file is lockable: if no files are listed as lockable, then no files are lockable.

Let's add an option for our filters to specify the default value if no patterns match.  If that default is false, like it should be for locking, then skip traversing the exclude patterns altogether, since anything that's not included cannot change the result.  We test both the case that lockable patterns are present and absent in our test.

Fixes #4169

### CODE REVIEW

File: filepathfilter/filepathfilter.go [hunk 1]
```diff
@@ -16,18 +16,35 @@ type Pattern interface {
...
-func New(include, exclude []string) *Filter {
+type option func(*options)
+
+func DefaultValue(val bool) option {
+	return func(args *options) {
+		args.defaultValue = val
+	}
+}
+
+func NewFromPatterns(include, exclude []Pattern, setters ...option) *Filter {
```
Comment (chrisd8088) [inline filepathfilter/filepathfilter.go:36]: I like that you've made this more generic than just adding a simple `bool` flag parameter.

File: filepathfilter/filepathfilter.go [hunk 2]
```diff
@@ -61,7 +78,7 @@ func (f *Filter) Allows(filename string) bool {
 		}
 	}
 
-	if !included && len(f.include) > 0 {
+	if !included && (len(f.include) > 0 || !f.defaultValue) {
 		tracerx.Printf("filepathfilter: rejecting %q via %v", filename, f.include)
```
Comment (chrisd8088) [inline filepathfilter/filepathfilter.go:82]: If `len(f.include) == 0` but `f.defaultValue` is `false`, then we'll return `false` here, which is intended, obviously, but the trace message may be confusing as `f.include` will be empty.  I might recommend adding some additional logic here to output a more meaningful trace message when we're rejecting the match because we fell through to the filter's default value.

File: filepathfilter/filepathfilter.go [hunk 3]
```diff
@@ -16,18 +16,35 @@ type Pattern interface {
...
-func NewFromPatterns(include, exclude []Pattern) *Filter {
-	return &Filter{include: include, exclude: exclude}
+type options struct {
+	defaultValue bool
 }
 
-func New(include, exclude []string) *Filter {
+type option func(*options)
+
+func DefaultValue(val bool) option {
```
Comment (chrisd8088) [inline filepathfilter/filepathfilter.go:30]: My only hesitation here is that `DefaultValue` is something of a generic phrase and, while I have no good alternatives to suggest, I wondered if we could add a comment describing it's function, at least.

I think my hesitation stems from the fact that, IIUC, this isn't so much a default in the sense of "if no patterns match, then do X" but rather "if no **_include_** patterns are **_defined_**, then do X".  So it feels more specific than a generic default ... maybe there's a way to express that in a different name, like `NoIncludeDefaultValue`?  Sheesh, naming things is hard.  :-(

File: filepathfilter/filepathfilter.go (hunk 1 above)
Comment (bk2204) [reply filepathfilter/filepathfilter.go:36]: Besides the design benefits, this also has the benefit of not requiring us to retrofit every other caller in the codebase.

File: filepathfilter/filepathfilter.go (hunk 3 above)
Comment (bk2204) [reply filepathfilter/filepathfilter.go:30]: True, we only consider include patterns, but this is an optimization: if we know that the filter has only excludes left, the only thing we can return is `false` or the default value.  If the default value is `false`, then we need not consider the excludes at all, since we know what the return value is.  The optimization isn't required for correctness, but it's clear to me that we need multiple additional comments here, since this is tricky to reason about.

Comment (bk2204) [reply filepathfilter/filepathfilter.go:32]: I've added a comment here explaining what `DefaultValue` does and explained the logic here much better.

Comment (chrisd8088) [reply filepathfilter/filepathfilter.go:32]: Thanks, and I think I noticed the logic changed too to make it more clearer as well!  ❤️
