### PR TITLE
Fix hang in prune with too few file descriptors

### LINKED ISSUE #3403: `git lfs prune` hangs
First up, I know that this looks like a duplicate of #1494, #3095, or #1860. However, the first is a really old issue, wherein it was asked to create a new issue to reproduce, which happened in #3095. This in turn was closed since the submitter could no longer reproduce, and #1860 was resolved long ago, and I am seeing the issue in:
```
12:14 $ git lfs env
git-lfs/2.6.0 (GitHub; darwin amd64; go 1.11.2)
git version 2.19.2
```

Each time that I run `GIT_TRACE=2 git lfs prune`, it hangs with the same last lines of output (obviously with different timestamps!):

```
12:07:39.385073 trace git-lfs: RETAIN: 11625cc4f64165de32eba059e310a7b7caf89dfa3e4c34432a222833320d9208 unpushed
12:07:39.385079 trace git-lfs: RETAIN: 2c0048ab3ce75a202f692b159d6aa0a68edce3e4e4c5123a3359a38b29faa6b1 unpushed
12:07:39.385088 trace git-lfs: RETAIN: d29825317cfc2a0316c2d3182222f223e55a44a193c2738f607b19af8930a715 unpushed
12:07:39.385134 trace git-lfs: RETAIN: 6108a2e9db3a84fba7875339948230e99f62bb674fc2baa2c1e24717148c7e27 unpushed
12:07:39.385164 trace git-lfs: RETAIN: 11625cc4f64165de32eba059e310a7b7caf89dfa3e4c34432a222833320d9208 unpushed
12:07:39.414052 trace git-lfs: RETAIN: 2c0048ab3ce75a202f692b159d6aa0a68edce3e4e4c5123a3359a38b29faa6b1 unpushed
```

At this point it just seems to hang. When I do a `top`, there is no CPU, nor disk activity. I have roughly 100 git processes running, and they never change, the processes that I have are:

```
12:19 $ ps -ef | grep git | cut -c 55- | sort | uniq -c
   1 /usr/local/bin/git-lfs prune
  47 git -c filter.lfs.smudge= -c filter.lfs.clean= -c filter.lfs.process= -c filter.lfs.required=false cat-file --batch-check
  65 git -c filter.lfs.smudge= -c filter.lfs.clean= -c filter.lfs.process= -c filter.lfs.required=false rev-list --stdin --objects --no-walk --
   1 git lfs prune
   1 grep git
```

There are no error messages to the console, and `run_command` doesn't seem to fail:

```
12:27 $ GIT_TRACE=1 git lfs prune 2>&1 | grep run_command
12:27:51.879582 run-command.c:643       trace: run_command: git-lfs prune
12:27:51.927361 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.096859 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.098864 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.100725 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.100752 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.100848 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.102625 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.108344 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.108923 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.114106 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.096778 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.123233 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.127792 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.128629 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.128834 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.129020 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.129218 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.129413 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.135609 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.127644 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.137172 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.137361 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.137425 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.117740 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.152899 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.145751 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.145817 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.145872 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.145904 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.169447 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.148367 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.169663 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.148553 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.172637 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.173596 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.173645 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.173982 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.179396 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.181824 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.182053 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.185531 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.186667 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.186775 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.191342 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.178278 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.198348 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.186284 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.187159 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.211047 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.224592 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.233195 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.237940 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.246638 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.246966 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.250340 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.250400 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.249924 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.250036 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.250232 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.292630 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.298152 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.300480 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.302367 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.302923 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.302962 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.303253 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.304354 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.312135 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.314990 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.310116 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.311425 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.311771 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.320211 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.311219 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.310287 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.310477 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.311621 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.311966 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.310684 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.310863 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.311025 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.325683 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.326400 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.326790 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.327123 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.335204 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.335422 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.342640 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.348342 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.352581 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.352641 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.352918 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.352974 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.353522 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.353907 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.354152 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.354396 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.354647 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.354904 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.355155 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.355752 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.357335 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.365233 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.367492 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.369284 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.376712 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.376741 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.376848 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.376931 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.377058 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.377115 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.377177 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.377217 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.377304 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.377358 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.377884 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.378627 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.379115 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.379323 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.379479 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.379986 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.384330 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.384414 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.384557 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.384731 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.384957 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.385188 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.385435 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.385682 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.384528 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.386179 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.389760 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.402318 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.410528 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.410618 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.410705 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.410808 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.410884 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.411088 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.411179 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
12:27:52.432284 trace git-lfs: run_command: git rev-list --stdin --objects --no-walk --
```

I cannot provide a reproduction outside of my checkout, but I can run tests against my checkout if there are any tests that could be run for more information.

### PR DESCRIPTION
**Pull request by bk2204**
When running `git lfs prune`, we spawn a large number of goroutines, each of which may spawn two processes and consume several file descriptors for the processes' pipes. This means it's very easy for us to run ourselves out of file descriptors, especially if we have a limit set with ulimit.

Use a semaphore to limit the number of processes in use at once, at least until we move the handing of this code in-process in a future commit.

In addition, if we hit this case, report errors.

Finally, close objects to release some additional file descriptors.

This fixes #3403.

### CODE REVIEW

File: lfs/gitscanner_catfilebatch.go [hunk 1]
```diff
@@ -41,8 +42,10 @@ func runCatFileBatch(pointerCh chan *WrappedPointer, lockableCh chan string, loc
 			}
 		}
 
-		if err := revs.Wait(); err != nil {
-			errCh <- err
+		if canScan {
```
Comment (PastelMobileSuit) [inline lfs/gitscanner_catfilebatch.go]: I'm unfamiliar with this code so I'm a bit confused as to how this accomplishes what's listed in the commit message. Could you elaborate?

Comment (bk2204) [reply lfs/gitscanner_catfilebatch.go]: Sure. If, for some reason, the scanner fails, such as running out of file descriptors, it returns false from `Scan`. In such a case, the thread producing values on `revs.Results` will be expecting us to read more objects from the data channel and will not have closed the error channel. However, this thread isn't reading anything from the data channel, and is waiting on the error channel, and will continue to do so until it's closed.

Since this thread is waiting on the error channel to have data or be closed, and the other thread is waiting to write to the data channel, we deadlock whenever `Scan` returns false. This prevents the return of the useful error message to the user and results in a hang; therefore, this commit is more about returning a useful error message in case of failure instead of hanging.

Comment (PastelMobileSuit) [reply lfs/gitscanner_catfilebatch.go]: Ah okay, that makes a lot of sense. Thanks for the info!
