### PR TITLE
Ensure correct syntax for commit headers in lfs migrate import

### LINKED ISSUE #3310: Import with `--no-rewrite` option adds incorrect commit timestamp
I've tried to use the import migration mode and this added in a new commit with the following date:

```shell
Date:   Thu Jan 1 00:00:00 1970 +0000 
```

The migration used is the following:

```shell
git lfs migrate import --no-rewrite -m'Commit message...' path/to/files/*.png
```
This can be replicated without the commit message, too.

### PR DESCRIPTION
**Pull request by bk2204**
We accidentally wrote ill-formed commit headers when writing commits for `git lfs migrate import --no-rewrite` because the author and committer fields lacked timestamps.  In addition, we could write empty email addresses if the user did not have a `user.email` field set but instead used the `EMAIL` environment variable to set their email.

Correct both of these issues and honor the distinction between author and committer.  Note that due to limitations of the Go standard library, this series does not honor `GIT_AUTHOR_DATE` and `GIT_COMMITTER_DATE` even though it honors the name- and email-related environment variables; this will be tracked in #3312.

This fixes #3310.

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -483,13 +483,48 @@ func (c *Configuration) loadGitConfig() {
...
+	email, ok = c.Os.Get("GIT_" + envType + "_EMAIL")
+	if !ok {
+		email, ok = c.Git.Get("user.email")
+	}
+	if !ok {
+		email, _ = c.Os.Get("EMAIL")
+	}
+
+	// Git filters certain characters out of the name and email fields.
+	name = strings.Map(filterString, name)
```
Comment (ttaylorr) [inline config/config.go]: Nice use of `strings.Map`. I think that `filterString` is too generically named to be exposed privately at the package-level scope. What do you think about either clarifying the name (perhaps, `filterSignatureString`) or introducing the function within this function scope, like:

```go
func (c *Configuration) findUserData(envType string) (name, email string) {
        var filter func(rune) rune = func(r rune) rune {
                // ...
        }

        name = strings.Map(filter, name)
}
```

File: t/t-migrate-import-no-rewrite.sh [hunk 2]
```diff
@@ -33,6 +33,9 @@ begin_test "migrate import --no-rewrite (default branch)"
   # Ensure a new commit message was generated based on the list of imported files
   commit_msg="$(git log -1 --pretty=format:%s)"
   echo "$commit_msg" | grep -q "a.txt: convert to Git LFS"
+
+  # Ensure we write a valid commit object.
+  git fsck
```
Comment (ttaylorr) [inline t/t-migrate-import-no-rewrite.sh]: ✨

File: config/config.go (hunk 1 above)
Comment (bk2204) [reply config/config.go]: Yeah, I was worried about that.  I think the nested function is the way to go.  I'll make that change.
