### PR TITLE
Fix `lfs unlock --force` on a missing file

### LINKED ISSUE #1925: lfs unlock requires the file to exist locally
I think passing `--force` should remove the lock regardless.

### PR DESCRIPTION
**Pull request by technoweenie**
Fixes #1925

### CODE REVIEW

File: commands/command_lock.go [hunk 1]
```diff
@@ -72,15 +72,18 @@ func lockPath(file string) (string, error) {
 
 	abs := filepath.Join(wd, file)
 	path := strings.TrimPrefix(abs, repo)
+	if len(path) > 1 {
```
Comment (ttaylorr) [inline commands/command_lock.go]: Is this to trim off the leading `/`? I think this should be fine to change since we don't have any production implementations in the wild right now, but maybe a clarifying comment, or something like:

```go
path = strings.TrimPefix("/", path)
```

would be good.

File: test/test-unlock.sh [hunk 2]
```diff
@@ -19,6 +19,32 @@ begin_test "unlocking a lock by path"
 )
 end_test
 
+begin_test "force unlocking lock with missing file"
+(
+  set -e
+
+  reponame="force-unlock-missing-file"
+  setup_remote_repo_with_file "$reponame" "a.dat"
```
Comment (ttaylorr) [inline test/test-unlock.sh]: Ha, so glad these are repo-local now 🙌 .

File: test/test-unlock.sh [hunk 3]
```diff
@@ -19,6 +19,32 @@ begin_test "unlocking a lock by path"
...
+
+  GITLFSLOCKSENABLED=1 git lfs lock "a.dat" | tee lock.log
+  id=$(grep -oh "\((.*)\)" lock.log | tr -d "()")
```
Comment (ttaylorr) [inline test/test-unlock.sh]: Definitely outside the scope of this PR, but we should perhaps extract this out to a function, since this `grep | tr` business is a tinge confusing. This one's on me, since I think I wrote this a while ago.

File: test/test-unlock.sh [hunk 4]
```diff
@@ -19,6 +19,32 @@ begin_test "unlocking a lock by path"
...
+  assert_server_lock "$reponame" "$id"
+
+  git rm a.dat
+  git commit -m "a.dat"
+  rm *.log *.json # ensure clean git status
+  git status
```
Comment (ttaylorr) [inline test/test-unlock.sh]: Does `git status` exit with a non-zero code if there are modified files? If not, we should probably `grep` through the output of this.

Comment (technoweenie) [inline test/test-unlock.sh]: No, I just left this here for a bit of additional debugging in case there's a failure.

File: test/test-unlock.sh (hunk 3 above)
Comment (technoweenie) [inline test/test-unlock.sh]: Sure, sounds good.

File: test/test-unlock.sh (hunk 4 above)
Comment (ttaylorr) [inline test/test-unlock.sh]: Ah, cool -- thanks for explaining 👍 .
