### PR TITLE
Honor GIT_WORK_TREE

### LINKED ISSUE #4213: git lfs track does not honor GIT_WORK_TREE and GIT_DIR
**Describe the bug**
`git lfs track` does not honor `GIT_WORK_TREE` nor `GIT_DIR` environment variables as well as `--git-dir` and `--work-tree` options.

**To Reproduce**
```
mkdir foo bar
export GIT_WORK_TREE=foo GIT_DIR=bar
git init
git lfs track '*.xz'
```
`.gitattributes` file is produced in current directory and error message is printed:
> Tracking "*.xz"
> Error changing lockable file permissions: Error in git ls-files -z --others --cached --exclude-standard: exit status 128 fatal: not a git repository: 'bar'
>
> Errors logged to <…>/testtwo/bar/lfs/logs/20200814T181926.04705318.log
> Use `git lfs logs last` to view the log.

**Expected behavior**
`.gitattributes` file in `foo` directory.

**System environment**
Linux, git version 2.28.0, git-lfs/2.11.0 (GitHub; linux amd64; go 1.14.4)

**Output of `git lfs env`**
```
git-lfs/2.11.0 (GitHub; linux amd64; go 1.14.4)
git version 2.28.0

LocalWorkingDir=/home/hideo/testtwo/foo
LocalGitDir=/home/hideo/testtwo/bar
LocalGitStorageDir=/home/hideo/testtwo/bar
LocalMediaDir=/home/hideo/testtwo/bar/lfs/objects
LocalReferenceDirs=
TempDir=/home/hideo/testtwo/bar/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/hideo/testtwo/bar/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_DIR=bar
GIT_EXEC_PATH=/usr/lib/git-core
GIT_NOTES_REF=refs/notes/build
GIT_WORK_TREE=foo
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

### PR DESCRIPTION
**Pull request by bk2204**
Currently, we don't honor GIT_WORK_TREE like Git does.  Git implicitly changes into the working tree of the repository if this variable is set, but we currently don't do that.

Let's fix that by mimicking Git's behavior so this works correctly, which necessitates transforming the various environment variables we pass to Git so that they are valid when we change directories.

These commits are logical, bisectable, and independent and have sane commit messages.

Fixes #4213
/cc @Mr-Tao as reporter

### CODE REVIEW

File: lfs/lfs.go [hunk 1]
```diff
@@ -72,10 +76,15 @@ func Environ(cfg *config.Configuration, manifest *tq.Manifest) []string {
 	}
 
 	for _, e := range osEnviron {
-		if !strings.Contains(strings.SplitN(e, "=", 2)[0], "GIT_") {
+		key := strings.SplitN(e, "=", 2)[0]
+		if !strings.Contains(key, "GIT_") {
```
Comment (chrisd8088) [inline lfs/lfs.go:80]: Just looking at this with fresh eyes, I wonder if `strings.HasPrefix()` would be more appropriate ... are there environment variables where `GIT_` would not be at the start of the name?

File: commands/commands.go [hunk 2]
```diff
@@ -315,15 +315,49 @@ func requireInRepo() {
...
+
+func setupWorkingCopy() {
+	requireInRepo()
+	requireWorkingCopy()
+	changeToWorkingCopy()
+}
+
+func changeToWorkingCopy() {
+	workingDir := cfg.LocalWorkingDir()
+	cwd, err := os.Getwd()
```
Comment (chrisd8088) [inline commands/commands.go:345]: IIUC, the path which we get for the current working directory will be compared down below (after running `filepath.EvalSymlinks()` on it) to the output from `cfg.LocalWorkingDir()` which I believe [ultimately](https://github.com/git-lfs/git-lfs/blob/68a8f8a49d834c91c9e9d39bc53c6fc065122dbd/config/config.go#L368) comes from `git.GitAndRootDirs()`which as of 23fd6c5973b69694776e630e11eda48bfe1f838c is now always going to call the new `tools.CanonicalizePath()` which will call `TranslateCygwinPath()`.

So in order to also run `TranslateCygwinPath()` on the output from `os.Getwd()`, perhaps this should instead call `tools.Getwd()`?

**Review by chrisd8088 — APPROVED** [review]
This is great, thank you!  I had a couple of minor comments, but otherwise LGTM!

File: lfs/lfs.go (hunk 1 above)
Comment (bk2204) [reply lfs/lfs.go:80]: Yeah, this is a behavior change, but I believe it's a prudent change to make.

File: commands/commands.go (hunk 2 above)
Comment (bk2204) [reply commands/commands.go]: Good point.  Updated.
