### PR TITLE
tools: add RobustRemove() for Windows to handle file lock errors

### LINKED ISSUE #6157: Access denied during `git lfs pull` for some objects
**Describe the bug**

We updated our git lfs version to 3.7.1 and some of our repositories struggle with checking out LFS files on Windows. With git-lfs 3.7.0 there was no such problem.

**To Reproduce**

We have no influence on the following commands as this is done by the gitlab-runner custom executor we're relying on:

```powershell
$env:GIT_LFS_SKIP_SMUDGE="1"
git init C:/users/nice/desktop/mypkg --template C:\gitlab-runner\builds\mypkg.tmp\git-template
cd C:\users\nice\desktop\mypkg
git remote add origin https://internal-url.com/mypkg.git
git fetch origin --no-recurse-submodules +refs/heads/master --depth 20 --prune --quiet
git -c submodule.recurse=false checkout -f -q master
git clean -ffdx
git lfs pull
```

The `git lfs pull` command fails with:

```log
could not check out "tests/testdata/cs.foobar_clean-1.2.3-py3-none-any.whl": could not create working directory file "tests/testdata/cs.foobar_clean-1.2.3-py3-none-any.whl": open C:\Users\nice\Desktop\mypkg\tests\testdata\cs.foobar_clean-1.2.3-py3-none-any.whl: Access is denied.
```

The `.gitattributes` file looks like:

```
tests/testdata/*.egg filter=lfs diff=lfs merge=lfs -text
tests/testdata/*.whl filter=lfs diff=lfs merge=lfs -text
```
... and all files are properly tracked.

BTW: A second `git lfs pull` works just fine

**Expected behavior**

It should work just like it did with 3.7.0

**System environment**

```
Windows Server >= 2019
```

Windows defender exclusions are set to exclude the builds and mypkg directories

The same repositories do not fail when run on Windows 11 with the "same" setup.

**Output of `git lfs env`**
```
git-lfs/3.7.1 (GitHub; windows amd64; go 1.25.1; git b84b3384)
git version 2.52.0.windows.1

Endpoint=https://internal-url.com/mypkg.git/info/lfs (auth=none)
LocalWorkingDir=C:\Users\nice\Desktop\mypkg
LocalGitDir=C:\Users\nice\Desktop\mypkg\.git
LocalGitStorageDir=C:\Users\nice\Desktop\mypkg\.git
LocalMediaDir=C:\Users\nice\Desktop\mypkg\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\nice\Desktop\mypkg\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneVerifyUnreachableAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\nice\Desktop\mypkg\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_LFS_SKIP_SMUDGE=1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

### PR DESCRIPTION
**Pull request by stanhu**
Add RobustRemove() function that retries on ERROR_SHARING_VIOLATION and ERROR_ACCESS_DENIED, using the same delay pattern as Git on Windows (0, 1, 10, 20, 40 ms). This works around "Access is denied" errors during git lfs pull when antivirus or file indexers hold files open.

Closes #6157

### CODE REVIEW

File: tools/robustio_windows.go [hunk 1]
```diff
@@ -16,6 +17,24 @@ func isEphemeralError(err error) bool {
...
 
+// isFileInUseError returns true if remove err may be resolved by waiting.
+// See https://github.com/git/git/blob/7f19e4e1b6a3ad259e2ed66033e01e03b8b74c5e/compat/mingw.c#L162-L171.
+func isFileInUseError(err error) bool {
+	return errors.Is(err, windows.ERROR_SHARING_VIOLATION) ||
+		errors.Is(err, windows.ERROR_ACCESS_DENIED)
+}
+
+// removeRetryOptions uses the same delay pattern as Git on Windows.
+// See https://github.com/git/git/blob/7f19e4e1b6a3ad259e2ed66033e01e03b8b74c5e/compat/mingw.c#L243.
```
Comment (chrisd8088) [inline tools/robustio_windows.go:28]: Thanks for updating the link in the comment to point to the corresponding part of Git's retry logic!

If this PR doesn't also implement the same `Unlink of file '%s' failed. Should I try again? (y/n)` [prompt](https://github.com/git/git/blob/7f19e4e1b6a3ad259e2ed66033e01e03b8b74c5e/compat/mingw.c#L479-L480) that Git [asks](https://github.com/git/git/blob/7f19e4e1b6a3ad259e2ed66033e01e03b8b74c5e/compat/mingw.c#L231) the user when the automatic retries are exhausted, then we should expand our code comments to note that difference.

The same is true if we choose not to support the `GIT_ASK_YESNO` environment variable; we should document that decision in our comments.

File: tools/robustio_windows.go [hunk 2]
```diff
@@ -16,6 +17,24 @@ func isEphemeralError(err error) bool {
...
+var removeRetryOptions = []retry.Option{
+	retry.Delay(0),
+	retry.Delay(1 * time.Millisecond),
+	retry.Delay(10 * time.Millisecond),
+	retry.Delay(20 * time.Millisecond),
+	retry.Delay(40 * time.Millisecond),
```
Comment (chrisd8088) [inline tools/robustio_windows.go]: This looks like such a clean implementation, I was really hoping it would work to mirror Git's behaviour!

Unfortunately, I don't think it will.

I ran a small test program which passes multiple `Delay()` option functions, and only the last one takes effect because the option functions are [run](https://github.com/avast/retry-go/blob/2.4.2/retry.go#L90-L92) in the order they are passed to the `Do()` function.  So the final `Delay()` option function [overwrites](https://github.com/avast/retry-go/blob/2.4.2/options.go#L48) the internal `delay` configuration setting that the previous option functions set to smaller values.  Here's my example program:

```go
package main

import (
	"errors"
	"fmt"
	"time"

	"github.com/avast/retry-go"
)

func main() {
	retry.Do(
		func() error {
			fmt.Println(time.Now().Format("15:04:05"))
			return errors.New("oops")
		},
		retry.Delay(0),
		retry.Delay(1 * time.Second),
		retry.Delay(5 * time.Second),
	)
}
```

In my example, this means the first retry delay is 5 seconds, not 0 or 1 seconds.  Then because the [default](https://github.com/avast/retry-go/blob/2.4.2/retry.go#L85) `delayType` configuration setting is `BackOffDelay`, each subsequent delay period is [twice](https://github.com/avast/retry-go/blob/2.4.2/options.go#L62) the previous one:

```
18:59:50
18:59:55
19:00:05
19:00:25
19:01:05
19:02:25
19:05:05
19:10:25
```

We use an older 2.4.2 version of the `github.com/avast/retry-go` package, so we could certainly upgrade to the latest 5.0.0 version if that was helpful.  I'm not sure it's necessary, though, as I think something more like this could work.  Here's another example program, and its output:

```go
package main

import (
	"errors"
	"fmt"
	"time"

	"github.com/avast/retry-go"
)

var delaySecs = [5]int{0, 1, 10, 20, 40}

func main() {
	retry.Do(
		func() error {
			fmt.Println(time.Now().Format("15:04:05"))
			return errors.New("oops")
		},
		retry.Attempts(6),
		retry.DelayType(func(n uint, config *retry.Config) time.Duration {
			return time.Duration(delaySecs[n]) * time.Second
		}),
	)
}
```

```
21:48:46
21:48:46
21:48:47
21:48:57
21:49:17
21:49:57
```

So here we set a maximum of 6 attempts, and provide our own anonymous `DelayTypeFunc` function to calculate the next delay interval.  That seems to work as we'd like (except that I'm using seconds in my examples, not milliseconds).

I'll suggest a change to the `RobustRemove()` function below based on this experiment.

File: tools/robustio_windows.go [hunk 3]
```diff
@@ -38,3 +57,12 @@ func RobustOpen(name string) (*os.File, error) {
 		retry.LastErrorOnly(true),
 	)
 }
+
+func RobustRemove(path string) error {
+	return retry.Do(
+		func() error {
+			return os.Remove(path)
+		},
+		append(removeRetryOptions, retry.RetryIf(isFileInUseError))...,
```
Comment (chrisd8088) [inline tools/robustio_windows.go]: Here's what I would suggest instead, which I think will get us closer to what we would like:

```suggestion
		retry.RetryIf(isFileInUseError),
		retry.DelayType(func(n uint, config *retry.Config) time.Duration {
			return time.Duration(robustRemoveRetryDelaysMs[n]) * time.Millisecond
		}),
		retry.Attempts(uint(len(robustRemoveRetryDelaysMs)+1)),
		retry.LastErrorOnly(true),
```

with an array defined like this:

```go
var robustRemoveRetryDelaysMs = [5]int{0, 1, 10, 20, 40}
```

**Review by chrisd8088 — COMMENTED** [review]
Hey, thanks for taking the time to tackle this enhancement!

I made some suggestions which I believe will be necessary, based on running a few tests.

Aside from that, I think it's OK for us to start with a simpler implementation which doesn't try to prompt the user the way Git does if all the automatic retry attempts fail.  We can always add that logic, and possibly also support for the `GIT_ASK_YESNO` environment variable, in a future PR.

Thanks again for trying to help improve the experience on older Windows systems!

File: tools/robustio_windows.go (hunk 3 above)
Comment (stanhu) [reply tools/robustio_windows.go]: Thanks for looking at this in detail!

**Review by chrisd8088 — APPROVED** [review]
This looks great, thank you!

**Comment by stanhu** [comment]
Thanks @chrisd8088! 

@git-lfs/releases Is there a timeline for the next git-lfs release?

**Comment by chrisd8088** [comment]
> Is there a timeline for the next git-lfs release?

Yes, we're expecting to make a release shortly.  There are more details in my reply to #6253.  It won't be this week due to outside factors, so we are now targeting the first part of May.
