### PR TITLE
lfsapi: handle SSH hostnames and aliases without users

### LINKED ISSUE #278: Using SSH shorthands as git remote should work the same as a full hostname
`git-lfs` behaves differently when you use an SSH shorthand vs. a full hostname as your git remote, even if they log in over SSH in the same way.

When I use an SSH shorthand I can't get `git-lfs` to upload binary files, whereas it works just fine when I use the full hostname definition. Looking at the gitolite log everything seems identical except the fact that `git-lfs` never runs `git-lfs-authenticate` when using a shorthand notation.

My SSH config:

``` config
host ytec
    user git
    hostname odin.ytec.nl
```

Uploading with a shorthand:

``` bash
$ git remote -v
origin  ytec:testing (fetch)
origin  ytec:testing (push)

$ git push --set-upstream origin master                                                                                                                                        
(0 of 1 files) 0 B / 1.29 MB  0.00 %
Username for '://':
```

Uploading without a shorthand:

``` bash
$ git remote -v
origin  git@odin.ytec.nl:testing (fetch)
origin  git@odin.ytec.nl:testing (push)

$ git push --set-upstream origin master
(1 of 1 files) 1.29 MB / 1.29 MB  100.00 %
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 390 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
To git@odin.ytec.nl:testing
   6b58b09..0898ce1  master -> master
Branch master set up to track remote branch master from origin.
```

Normal git works just fine fine with shorthands:

``` bash
quinox@duivenkracht:~/projects/testing_manual ^2 $ git ls-remote ssh://git@odin.ytec.nl/testing
0898ce13a2d0c4bd51a16fce42cbc0cce3d38661        HEAD

quinox@duivenkracht:~/projects/testing_manual ^2 $ git ls-remote ssh://ytec/testing            
0898ce13a2d0c4bd51a16fce42cbc0cce3d38661        HEAD
```

### LINKED ISSUE #2842: Cannot clone with non-default SSH key
_NOTE: In the following description I have changed some paths, project names,
and other identifying information, but left everything else intact._

_NOTE 2: I would be happy to help implement a solution but I don't have a lot
of time. I will try to provide a fix myself but any tips/advice to get me started
would be very much appreciated._

I am having an issue where LFS fails to download large files when I use a specific SSH
key implicitly via the SSH config file. None of the following issues arise if I 
use my default SSH key located at `~/.ssh/id_rsa` and `~/.ssh/id_rsa.pub`; that is, 
if I don't specify an SSH key and just clone from, say, 
`git@bitbucket.org:orgname/projectname.git`, LFS works just fine. This leads
me to believe that the following issue has to do with a bug in LFS, rather than
my configuration.

In order to seamlessly integrate multiple SSH keys into my Git workflow, 
I keep track of server/key associations using my `~/.ssh/config` file. 
For example:

```
Host bitbucket-personal
  HostName bitbucket.org
  User git
  IdentityFile ~/.ssh/id_rsa.personal
  IdentitiesOnly yes

Host bitbucket-work
  HostName bitbucket.org
  User git
  IdentityFile ~/.ssh/id_rsa.work
  IdentitiesOnly yes
```

Then, I have the following key pairs in my `~/.ssh` directory:

```
$ ls id_* -la | awk '{print $9}'
id_rsa.work
id_rsa.work.pub
id_rsa.personal
id_rsa.personal.pub
```

This allows me to use different keys for different repositories:

```
git clone bitbucket-work:orgname/work-project.git # clones a work-related repo using my work key
git clone bitbucket-personal:jake/personal-project.git # clones a personal project repo using my personal key
```

Unfortunately, this causes problems when the cloned repository has files commited with LFS. 
Below you will find the command line output followed by the full error log.

**Command Line Output**
```
$ git clone bitbucket-work:orgname/work-project.git
Cloning into 'work-project'...
remote: Counting objects: 7101, done.
remote: Compressing objects: 100% (2792/2792), done.
remote: Total 7101 (delta 5103), reused 6151 (delta 4228)
Receiving objects: 100% (7101/7101), 11.59 MiB | 1.44 MiB/s, done.
Resolving deltas: 100% (5103/5103), done.
Checking out files: 100% (1153/1153), done.
Downloading packages/PackageName/PackageLibrary.dll (478 KB)
Error downloading object: packages/PackageName/PackageLibrary.dll (deadbeef)                                                                                               : Smudge error: Error downloading packages/Atlas.DBLib/Interop.ATLAS_DBLib.dll (                                                                                               c7dc4024b6c32eb53765a3cfb35c98d7fd28a6aaa8c03260d95e928275734d36): batch request                                                                                               : missing protocol: "bitbucket-echo:echots/biv-braces.git/info/lfs"

Errors logged to C:\Code\orgname\work-project\.git\lfs\objects\logs\                                                                                               20180125T160052.6710708.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: packages/PackageName/PackageLibrary.dll: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Error Log**
```
git-lfs/2.3.4 (GitHub; windows amd64; go 1.8.3; git d2f6752f)
git version 2.16.1.windows.1

$ git-lfs.exe filter-process
Error downloading object: disable-restarts/disable-restart-task.pdf (a25f38e): Smudge error: Error downloading disable-restarts/disable-restart-task.pdf (a25f38e585dc2358b52c76684b419681a26e2b1d11de62f3688ac69892a4e1a0): batch request: missing protocol: "bitbucket-work:orgname/work-project.git/info/lfs"

missing protocol: "bitbucket-work:orgname/work-project.git/info/lfs"
batch request
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:170
github.com/git-lfs/git-lfs/errors.Wrap
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/errors.go:74
github.com/git-lfs/git-lfs/tq.(*tqClient).Batch
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/api.go:55
github.com/git-lfs/git-lfs/tq.Batch
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/api.go:37
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:426
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches.func1
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:348
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2197
Error downloading disable-restarts/disable-restart-task.pdf (a25f38e585dc2358b52c76684b419681a26e2b1d11de62f3688ac69892a4e1a0)
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:170
github.com/git-lfs/git-lfs/errors.Wrapf
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/errors.go:85
github.com/git-lfs/git-lfs/lfs.downloadFile
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:96
github.com/git-lfs/git-lfs/lfs.PointerSmudge
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:61
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer.go:64
github.com/git-lfs/git-lfs/commands.smudge
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:128
github.com/git-lfs/git-lfs/commands.filterCommand
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:116
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/run.go:68
main.main
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35
runtime.main
	C:/Go/src/runtime/proc.go:185
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2197
Smudge error
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:170
github.com/git-lfs/git-lfs/errors.NewSmudgeError
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:256
github.com/git-lfs/git-lfs/lfs.PointerSmudge
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:70
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer.go:64
github.com/git-lfs/git-lfs/commands.smudge
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:128
github.com/git-lfs/git-lfs/commands.filterCommand
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:116
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/run.go:68
main.main
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35
runtime.main
	C:/Go/src/runtime/proc.go:185
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2197

Current time in UTC: 
2018-01-26 00:23:06

ENV:
LocalWorkingDir=C:\Code\orgname\work-project
LocalGitDir=C:\Code\orgname\work-project\.git
LocalGitStorageDir=C:\Code\orgname\work-project\.git
LocalMediaDir=C:\Code\orgname\work-project\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Code\orgname\work-project\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Code\orgname\work-project\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
GIT_LFS_PATH=C:\Program Files\Git LFS
```

### PR DESCRIPTION
**Pull request by bk2204**
It's very common for a user to specify an SSH remote that refers to an
alias in their gitconfig file.  For example, if a user must use
different SSH keys when pushing to different remotes, setting different
aliases that use those different keys is the simplest and easiest way to
accomplish that goal.

Unfortunately, our parsing logic was broken for SSH remotes that used
bare SSH URLs (that is, without “ssh://”) with a hostname or alias, but
without a username component.  The URL parser we used saw the hostname
portion as the scheme of a URL, and we passed through any URLs with
unknown schemes.  This led to a failure to push, since we misparsed the
URL as a non-SSH URL and gave up when it also didn't look like an
HTTP(S) URL.

If we get an unknown “scheme” when parsing a URL, check if the URL uses a
remote helper (that is, it contains a double colon), and pass it
through.  Otherwise, do what Git does, and assume the URL is in fact an
SSH URL, and handle it accordingly.

We already handle the url.insteadof syntax properly, even if it looks
like a scheme.  Add tests that we continue to do so, and for the new
code and all the various permutations mentioned above.

This should fix #278 and also fix #2842.

### CODE REVIEW

File: lfsapi/endpoint_finder.go [hunk 1]
```diff
@@ -188,8 +188,17 @@ func (e *endpointGitFinder) NewEndpoint(rawurl string) Endpoint {
 	case "":
 		return endpointFromBareSshUrl(u.String())
 	default:
-		// Just passthrough to preserve
-		return Endpoint{Url: rawurl}
+		if strings.HasPrefix(rawurl, u.Scheme+"::") {
+			// Looks like a remote helper; just pass it through.
+			return Endpoint{Url: rawurl}
+		} else {
```
Comment (ttaylorr) [inline lfsapi/endpoint_finder.go]: Nit: we can drop this `} else {` and de-dent the below lines, since the `if` block returns unconditionally.

**Comment by ttaylorr** [comment]
> ✨ This looks great, @bk2204.

Thanks also for the detailed walkthrough of what's going on and how the changes works. I've always been somewhat wary of changing this part of the code, so your detailed message helped me build confidence that my understanding was correct.

File: lfsapi/endpoint_finder.go (hunk 1 above)
Comment (bk2204) [reply lfsapi/endpoint_finder.go]: You're right.  I'll fix that.
