### PR TITLE
git: avoid trying to rewrite remote tags as remote branches

### LINKED ISSUE #3818: git lfs migrate import --fixup not working; fatal error with "bad revisions"
```
herbst@PFC MINGW32 /e/git/project (master)
$ git lfs migrate import --fixup
migrate: Fetching remote refs: ..., done
Error in git rev-list --stdin --reverse --topo-order --do-walk --: exit status 1
28 fatal: bad revision '^refs/remotes/origin/Alpha-0.5'
migrate: Sorting commits: ..., done

$ git lfs version
git-lfs/2.6.1 (GitHub; windows 386; go 1.11.1; git dc072c3e)
```

See #3285 and #3281 which are closed and state that this is supposed to be fixed in lfs 2.6.0.

**Edit:** just updated to git-lfs 2.7.1 but the behaviour stays the same. Git version is 2.21.0.windows.1.

### PR DESCRIPTION
**Pull request by bk2204**
When invoking "git lfs migrate import --fixup", we call Git to fetch the remote branches and tags.  However, we mark both as having the type remote branch, so when we look up the local copies for them, we try to use the tag name as the name of a remote tracking branch, which fails.

Instead, let's mark them as remote tags, which means we won't try to rewrite them into branches at all.  This ensures the operation can succeed.

Fixes #3818

### CODE REVIEW

File: t/t-migrate-fixup.sh [hunk 1]
```diff
@@ -100,3 +100,34 @@ begin_test "migrate import (--fixup, --no-rewrite)"
...
+
+  git lfs install
+
+  cwd=$(pwd)
+  cd "$TRASHDIR"
+
+  git clone "$cwd" "$reponame-2"
+  cd "$reponame-2"
+
+  txt_oid="$(calc_oid "$(git cat-file -p :a.txt)")"
```
Comment (chrisd8088) [inline t/t-migrate-fixup.sh:127]: Is this line useful here?

Comment (bk2204) [reply t/t-migrate-fixup.sh:127]: No, it is not, and I'll remove it.

**Comment by bk2204** [comment]
It does still return the branches and tags, but we just don't use the tag values it returns.  I will fix the typo, though, while I'm here.
