### PR TITLE
locking: add flag to control modification of ignored files

### LINKED ISSUE #3390: git lfs sets ignored files to read-only when file type is marked as lockable
### Setup:
```
git version
git version 2.19.2.windows.1

git lfs version
git-lfs/2.6.0 (GitHub; windows amd64; go 1.11.1; git 93702d75)
```

- Git LFS is used for locking some binary files with the extention _.vw7_, so `.gitattributes` is set to `*.vw7 lockable`
- The project contains several .vw7 files which we lock when we need to change them and unlock after push
- In the project folder there is a folder named __output_ which is generated in the build process, it also contains _.vw7_ files
- This folder is ignored in git, `.gitignore` contains `_output`

### Problem:
For example when I run a `git checkout` of any file in the repository, all the _.vw7_ files in the __output_ folder are marked as read-only.
This causes any following build process to fail, as the build can't modify the _.vw7_ files in the __output_ folder. The files have to be manually set to writable to make it work again.

### Expected behaviour:
Files marked as lockable that are in an ignored folder should not be set to read-only

### PR DESCRIPTION
**Pull request by bk2204**
In a727fea2 ("locking: remove write permission for ignored files", 2018-08-20), we learned to set and clear the read-only attribute on ignored files that match the lockable pattern, since "git lfs lock" operates on pathspecs, not actual files.

However, in doing so, we caused a regression for people who have ignored files (such as build files) which match the lockable pattern, but should not have their permissions modified.  Since there is no easy way for us to know if the user would like their files modified, add a config option to control this behavior, and leave it at the historical (i.e., pre-a727fea2) default, off.  Add documentation accordingly.

Choosing the historical behavior is compatible with the most existing use cases and preserves the behavior people expect with Git, which is that it does not touch ignored files.

Fixes #3390.
/cc @ttaylorr 
/cc @zach-r-d #3183
/cc @Kitzibua #3390

### CODE REVIEW

File: t/t-lock.sh [hunk 1]
```diff
@@ -249,7 +249,33 @@ begin_test "lock with .gitignore"
...
+  git commit -m ".gitattributes: mark 'a.txt' as lockable"
+
   rm -f a.txt && git checkout a.txt
   refute_file_writeable a.txt
+
+  echo "*.txt" > .gitignore
+  git add .gitignore
+  git commit -m ".gitignore: ignore 'a.txt'"
+  rm -f a.txt && git checkout a.txt
+  assert_file_writeable a.txt
```
Comment (PastelMobileSuit) [inline t/t-lock.sh]: If I'm reading this option correctly, shouldn't `a.txt` be locked due to the `lfs.lockignorefiles=true`?

Comment (bk2204) [reply t/t-lock.sh]: Thanks for catching this. I typoed the config option a couple lines earlier.

**Comment by ali562** [comment]
#434
